### ISSUE TITLE
Menu does not show when double-clicking a paragraph

### ISSUE THREAD

**Issue by sbstn87** [emvaized/selecton-extension#10]
Hi,

is it possible to make Selecton show up, when one double clicks a text paragraph? At the moment it disappears when I try to do it.

Below is what I mean:
![2021-06-19_07-40-32](https://user-images.githubusercontent.com/37237675/122632238-11278400-d0c1-11eb-93f1-a028074326d6.gif)

**Comment by emvaized** [comment]
Hey @sbstn87 
For me double clicking works fine. Maybe it's some another extension conflicting?
![dblclick-2021-06-19_18 30 01](https://user-images.githubusercontent.com/37851576/122647375-a4e26a00-d12c-11eb-974a-e12a62d0452a.gif)

**Comment by sbstn87** [comment]
Ok, I was a bit wrong in my description. It works when I double click to select one word, but it does not work when I triple-click to select a whole line/paragraph.

**Comment by emvaized** [comment]
Should be resolved in new version 3.2.4
