### ISSUE TITLE
It doesn't work in text box

### ISSUE THREAD

**Issue by simonbcn** [emvaized/selecton-extension#15]
```
Vivaldi v4.3.2439.65 (Stable channel) stable (64 bits)
Selecton v3.4.0
```
When I select text in a text box (_for example here_), the popup is not showed.

**Comment by emvaized** [comment]
Try enabling it under `Settings > Buttons > Use special panel for text fields`

**Comment by simonbcn** [comment]
ok, it was that. 
Anyway, if I double-click on a word to select it, the icon I see is only the paste icon. 
![image](https://user-images.githubusercontent.com/428231/142991005-96954139-1285-42f1-aabe-908aaa7c41ff.png)
If I select the word normally, it works fine:
![image](https://user-images.githubusercontent.com/428231/142991058-ffcd486d-07b9-4cd3-8303-90960d0c74a8.png)

**Comment by emvaized** [comment]
Hmm, yes - I guess that's how it currently works

**Comment by simonbcn** [comment]
But if I select a text (_either by double clicking or selecting the text by dragging the mouse_) the pop up menu should be the same, right?

**Comment by emvaized** [comment]
The thing is — these two are separate tooltips with different trigger mechanism. When you double-click on text field, single 'Paste' tooltip gets called on the first click, and on the second click the regular selection tooltip (with 'Cut' and 'Copy' buttons) is being rejected since single 'Paste' tooltip is already there.

**Comment by simonbcn** [comment]
ok, I understand. It's unnecesary to modify it then.

**Comment by emvaized** [comment]
What I can suggest however is ticking "Add 'Paste' only when field is empty" option — with this is on double-clicking in text fields seems to work just fine

**Comment by emvaized** [comment]
Also, when the mentioned option is unticked (e.g. "Paste" button appears on every click over text field), if double click the word twice then the correct tooltip will show up, which is another workaround for your problem

**Comment by emvaized** [comment]
Double and triple clicks should be handled better now in most recent git version
