### ISSUE TITLE
Sometimes doesn't respond to middle click in popup

### ISSUE THREAD

**Issue by simonbcn** [emvaized/selecton-extension#18]
```
Arch Linux
Google Chrome 96.0.4664.110
Selecton v3.4.1
```

I think this bug will be difficult to debug because it only happens sometimes. 
Sometimes when I select text and want to open several searches in new background tabs with middle-click, it doesn't work. It simply hides the popup without doing anything.
However, if I minimize and immediately restore the Google Chrome window, it works again.

**Comment by simonbcn** [comment]
![Screenshot_20211223_131907](https://user-images.githubusercontent.com/428231/147240648-1f4df6b0-6586-4985-b6a3-55151ab5a929.png)

It fails in the second popup, where the search engine icons are located. 
Next time it fails, I will test if it only fails on that second popup with the middle click or also with the left click. In the first popup (with the magnifying glass icon) it always works with the left click.

**Comment by emvaized** [comment]
Hi Simon,
So what's the current issue you're facing? That custom search options sometimes do not open new tab with the url set in configs?

**Comment by simonbcn** [comment]
I think it's a problem with Chrome itself. Because if I minimize and restore the window it works again.
