### ISSUE TITLE
Debug mode enabled by default

### ISSUE THREAD

**Issue by anthonyaxenov** [emvaized/selecton-extension#2]
`debugMode` should equal to `false` in public releases due to countless amount of debug messages in console which are useless for average user and unbearably interferes for another JS developers while debugging

https://github.com/emvaized/selecton-extension/blob/92851a6d8eb7409339c17c6ced6932b8fa094dba/index.js#L82

I also propose you to replace [such constructions](
https://github.com/emvaized/selecton-extension/blob/master/index.js#L1228-L1231):
```js
if (debugMode) {
  console.log('Detected selection tooltip on the website with following style:');
  console.log(elementStyle);
}
```
with
```js
if (debugMode) {
  console.log('Detected selection tooltip on the website with following style:', elementStyle);
}
```
Thus you will reduce amount of debug messages without loss of their quality

**Comment by emvaized** [comment]
Thanks, I changed it to `false` now - seems I just forgot about it in a hurry to release encoding bugfix as quick as possible :)
As for simplifying debug messages topic - yes, I guess it would be great; may rework those in future updates

**Comment by emvaized** [comment]
As for 2.1.9:

- Debug mode is off by default
- Restructured some debug messages so that they will take only 1 line (except those where console output is expected to be multi-line)
- Added debug mode switcher in settings
