### ISSUE TITLE
Export/import settings didn't work

### ISSUE THREAD

**Issue by jupiter104** [emvaized/selecton-extension#20]
Hi. First of all, I just want to say this is an excellent extension. The best I've found so far for copying and searching selected text quickly. Unfortunately, it doesn't have a lot of downloads or reviews yet. I hope that will change soon. Maybe it needs some marketing.

Anyway, I just want to report an issue I faced.

Initially, I installed this extension directly from the files on this GitHub page. Then, I tweaked the extension settings based on my liking. Later, I found the extension on Google Chrome store. So, I exported the extension settings to a .json file and then installed the Chrome store version. But when I tried to import the settings, the Import button was grayed out and it couldn't import the settings from the .json file. So, I had to tweak the settings all over again manually. I think the Export/import settings has a bug. Please, look into it. Thank you.

**Comment by emvaized** [comment]
Thanks for your kind words, it means a lot to me.

To import settings, you have to hit "Choose file" button first, and after that "Import" button should become available. Or did you mean that it remains greyed out even after you choose the file?
![2022-01-20_20-16](https://user-images.githubusercontent.com/37851576/150398044-46152b69-e798-4dd2-8f3a-3004f1b1b70f.png)
![2022-01-20_20-17](https://user-images.githubusercontent.com/37851576/150398063-9c3087c4-d5df-43ad-9555-c8fb91352cdd.png)

**Comment by jupiter104** [comment]
>

**Comment by jupiter104** [comment]
Yeah, that's what I meant. Even after selecting the import file, it was still grayed out.

**Comment by emvaized** [comment]
Could you please show the contents of the file you tried to import?

**Comment by jupiter104** [comment]
> I have a few ideas on what could have went wrong. Could you please try out the latest version from GitHub? If it still won't work, please share the contents of the file you were trying to import.

Looks like the problem only occurs if you export from the github version and try to import in the chrome store version. otherwise, import/export works fine if you only use the chrome store version.

**Comment by emvaized** [comment]
I suppose that export button functions the same in previous version of Chrome Web Store and in most recent version from GitHub. So it's all about whether import button works properly or not.

**Comment by emvaized** [comment]
In the new version 3.5.0, which is now uploaded in Chrome Web Store for review, import button should work properly. If you'll face new issues with it after update is approved, please reopen this issue.
