### ISSUE TITLE
Search query words are separated by %20 instead of +

### ISSUE THREAD

**Issue by jupiter104** [emvaized/selecton-extension#22]
I've noticed if you search multiple words using Selecton which are separated by space like "tall tree", it makes the query URL like this:

https://www.google.com/search?q=tall%20tree

But if you search after going to google.com and typing into the search box, Google makes the query like this:

https://www.google.com/search?q=tall+tree

The search still works though but I was wondering why %20 is being used instead of +

**Comment by emvaized** [comment]
That's because the search query gets uri-encoded in order to prevent issues on pages which don't use unicode encoding

**Comment by jupiter104** [comment]
Oh, I see. It's because of compatibility.
