### ISSUE TITLE
[Regression] Middle-click focus the new tab always

### ISSUE THREAD

**Issue by simonbcn** [emvaized/selecton-extension#27]
```
Firefox 97.0.1
Selecton 3.5.5
```
My "_Panel behavior_" settings:
![2022-02-18_15-01](https://user-images.githubusercontent.com/428231/154696898-ae1d448e-3ea0-4ba0-805e-59c07f82ccaf.png)

Although I have deactivated the closing of the panel when I press the middle button, it still closes.

**Comment by emvaized** [comment]
Weird, I couldn't reproduce it on my computer.  
Could you test the latest code from GitHub to see if it still persists? It also contains new fix for https://github.com//emvaized/selecton-extension/issues/25

**Comment by simonbcn** [comment]
I've changed the title. 
In this animated gif you can see the problem (_in the video I click the middle mouse button_):
![Peek 19-02-2022 09-20](https://user-images.githubusercontent.com/428231/154793014-5ea39e05-9c4c-46ee-a1fc-0cd6cd979362.gif)
It should stay on the page with the pop-up open but immediately switch to the new tab and the pop-up closes.

I have this option "_When a link, image or media file is opened in a new tab, switch to it immediately_" disabled in Firefox settings.

**Comment by simonbcn** [comment]
> Weird, I couldn't reproduce it on my computer. Could you test the latest code from GitHub to see if it still persists? It also contains a new fix for https://github.com//emvaized/selecton-extension/issues/25

How do I build the Firefox extension?

**Comment by emvaized** [comment]
https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/#reloading-a-temporary-extension

**Comment by emvaized** [comment]
> I've changed the title.
I'm kind of confused now. So you no longer experience the issue with popup always hidden on middle click?

**Comment by simonbcn** [comment]
Version 3.5.5: when I middle-click the mouse it immediately switches to the new tab and closes the pop-up.

Version git: when I middle-click the mouse it closes the pop-up.
![Peek 19-02-2022 10-11](https://user-images.githubusercontent.com/428231/154794606-e6995c4d-d38b-4ff3-b585-33e6e720adf5.gif)

**Comment by emvaized** [comment]
> Version git: when I middle-click the mouse it closes the pop-up.

Alright, I think I figured out what was the issue here. Now it should work fine.

**Comment by simonbcn** [comment]
Now it works well again (_git version_). :+1:

**Comment by emvaized** [comment]
Just uploaded new version 3.5.6, containing this fix.
