### ISSUE TITLE
Tooltip Horizontal Alignment Issue

### ISSUE THREAD

**Issue by sbozdemir** [emvaized/selecton-extension#29]
Selecting "No effect" as Tooltip Reveal effect in the settings causes a mis-alignment issue on tooltip. If you select another option other than the "No effect", everything works fine. 
![Picture1](https://user-images.githubusercontent.com/41501117/154913979-8ef02b23-56c8-493e-af0c-582408623d38.png)

**Comment by emvaized** [comment]
Thanks for pointing out! This should be easy to fix.

**Comment by emvaized** [comment]
Should be fixed in new version 3.5.6, which will be approved and released within a few days.
