### ISSUE TITLE
Adding Norwegian Currency

### ISSUE THREAD

**Issue by R-Sharafaldin** [emvaized/selecton-extension#3]
Hey there! Loving the add-on and amazed at the speed you're developing it at. 

Was wondering if it was possible to add Norwegian currency? NOK, the Norwegian Krone. You have both Swedish and Danish (currently using the Swedish one as an estimate) and feel it would be nice to have all three crowns.

**Comment by emvaized** [comment]
Sure!
Thanks for your suggestion - I will add support for NOK in the next update

**Comment by emvaized** [comment]
Added support for NOK (Norwegian krone) currency in the new 2.1.9 version
