### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by XTRA26** [emvaized/selecton-extension#30]
Hi, I am not a programmer; I tried to edit code to open in background tab but failed.

Please make a option to open in background tab ( middle click is not suitable for me)
 and minor suggestion

instead of paste clipboard item on text field, in windows, windowskey+v ( clipboard history window) to choose older clipboard item

Thanks for good utility.

**Comment by emvaized** [comment]
> instead of paste clipboard item on text field, in windows, windowskey+v ( clipboard history window) to choose older clipboard item

Not possible.


> Please make a option to open in background tab ( middle click is not suitable for me)

In new version 3.5.9 there will be an option under 'Behavior' > 'Left click opens link as background tab', which changes behavior to what you requested.

**Comment by DasKashi** [comment]
> > Please make a option to open in background tab ( middle click is not suitable for me)
> 
> In new version 3.5.9 there will be an option under 'Behavior' > 'Left click opens link as background tab', which changes behavior to what you requested.

did this feature get removed again at some point?
