### ISSUE TITLE
Translation button is sometimes not shown

### ISSUE THREAD

**Issue by simonbcn** [emvaized/selecton-extension#31]
```
Firefox 98.0.2
Selecton 3.5.8
```

I've found this problem in this page: https://www.sundhed.dk/borger/guides/find-behandler/?RegionId=1083&MunicipalityId=630&InformationsUnderkategori=Hudl%C3%A6ge%20(dermato-venerolog)&Informationskategori=Speciall%C3%A6ge

![2022-03-23_09-29](https://user-images.githubusercontent.com/428231/159656273-89428d84-2b3a-4954-bf2f-5b6fa9cd6ef3.png)

But it does show it if I select only 1 or 2 words:
![2022-03-23_09-31](https://user-images.githubusercontent.com/428231/159656505-4d3bd298-ef8e-4bd0-bfee-7b76fb86ac25.png)

**Comment by emvaized** [comment]
Selecton by default tries to detect language of the selected text, and doesn't show the translate button if language is the same as user's, or could not be detected. You can configure this behaviour here:
<img width="397" alt="Снимок экрана 2022-03-23 в 23 40 15" src="https://user-images.githubusercontent.com/37851576/159800975-21fd6ad0-5b6a-4aa0-a5f7-e16a80fe774a.png">

**Comment by simonbcn** [comment]
I know, I have selected the same options:
![2022-03-24_08-53](https://user-images.githubusercontent.com/428231/159868440-b6c66d23-635f-45cc-9e1f-688535133d1c.png)

On the other hand, note that this is not the problem because if I select a single word it does show the translate button but if I select more it does not. 
I have only detected this problem, for the moment, on that page.

**Comment by emvaized** [comment]
Sorry for delay. It seems the text you selected was recognised as a code instead of plain text because of the hyphen in it.

**Comment by emvaized** [comment]
Should be fixed in 3.5.9
