### ISSUE TITLE
Wrong time conversion

### ISSUE THREAD

**Issue by Fan4Metal** [emvaized/selecton-extension#32]
10 AM EST is converted to 18:00, but should be 17:00 (advancing to EDT). Current time zone is GMT+3.

**Comment by emvaized** [comment]
Selecton currently relies on [toLocaleTimeString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString) method to convert to user's local time, which I guess uses browser built-in mechanisms. Maybe something wrong with your browser's or system's date-time settings?

**Comment by Fan4Metal** [comment]
I think the problem is that EST is usually corrected to EDT in most regions. So when you convert time at www.worldtimebuddy.com it is autocorrected to EDT. The same thing with CEST/CET time. Try to compare time conversion at [this](https://www.worldtimebuddy.com) site and Selecton  for example.

**Comment by emvaized** [comment]
Yes, I can confirm the problem.

**Comment by emvaized** [comment]
I just added manual check to change EST to EDT and CET to CEST if daylight saving time is active for user. Will land in next version 3.6.0

**Comment by Fan4Metal** [comment]
I still have encountered time conversion problem. [Here](https://play.toornament.com/en_GB/tournaments/5746985372982902784/rules) 10:00 AM EST is converted to 18:00, but should be 17:00 in my time zone (UTC+3).
