### ISSUE TITLE
pop up not clickable after last update

### ISSUE THREAD

**Issue by mabondanini** [emvaized/selecton-extension#45]
Installed in ms Edge via Chrome Web Store

**Comment by emvaized** [comment]
Thanks for reporting, I managed to reproduce it in MS Edge. Will publish a fix update today

**Comment by emvaized** [comment]
I think I found the reason of this problem. Will publish new 3.6.8 update now with quick fix

**Comment by mabondanini** [comment]
Great, thank you emvaized.  I take this opportunity to congratulate you on your excellent extension, it helps me a lot in my daily browser use.

**Comment by emvaized** [comment]
We're currently waiting until Google team approves new update 3.6.8, which is supposed to fix this problem. I hope it comes as soon as possible. As a temporary fix, you can disable `Appearance` > `Show arrow on bottom`, it will deactivate the part of code which seems to cause malfunction in 3.6.7.

**Comment by DanielEmerson33** [comment]
The new version installed itself just now and everything's back to normal. Thanks!

**Comment by emvaized** [comment]
Glad to hear!

**Comment by mabondanini** [comment]
> The new version installed itself just now and everything's back to normal. Thanks!

same for me, thank you

**Comment by emvaized** [comment]
Closing this issue now, as resolved

**Comment by mabondanini** [comment]
PS paypal refuses to make you a donation!... any workaround?
