### ISSUE TITLE
Version 3.6.7 Issues

### ISSUE THREAD

**Issue by DanielEmerson33** [emvaized/selecton-extension#46]
Selecton upgraded to Version 3.6.7 today and now the "copy" option doesn't work and the selection pop-up won't go away when you click elsewhere on the page. I haven't tested out all the other features, but some are definitely working as normal.

- Vivaldi: 5.5.2805.38 (Stable channel) (64-bit)
- OS: Windows 11

Please let me know what other information you need.

**Comment by StabiL** [comment]
On 3.6.8 it is still the same (load extension from unpacked folder in Opera). 
Chrome store still has the old version.

**Comment by emvaized** [comment]
Thanks for reporting. We're currently waiting until Google team approves new update, which is supposed to fix this problem. I hope it comes as soon as possible. As a temporary fix, you can disable `Appearance` > `Show arrow on bottom`, it will disable the part which causes malfunction in 3.6.7.

I'm closing this ticket as duplicate, let's continue discussion regarding this problem [here](https://github.com/emvaized/selecton-extension/issues/45).
