### ISSUE TITLE
Please show more meaningful error message when translation service cannot be reached

### ISSUE THREAD

**Issue by p1otr** [emvaized/selecton-extension#47]
I always get "No translation found" tooltip whenever I try to translate selected text (on button hover). I tried all 4 translation services. My user language is: "pl". Note that LMB on the button works fine (i.e. it redirects me to the right service with right translation)

**Comment by p1otr** [comment]
Update: It works if I disable "Hide translate button for user's language". My default language (in the browser and plugin's "User's language") is "pl" but I guess you check all languages from Accept-Language or something (I have "en" in Accept-Language as one of selected languages (default: pl, but I also have "en" and "de" over there).

**Comment by emvaized** [comment]
Hi! 
Live translation feature uses Google Translate as a source. Maybe you denied the extension access to this website?

**Comment by p1otr** [comment]
I didn't. It also worked for few minutes once I disabled "Hide translate button for user's language" - I didn't change anything and it's not working again

**Comment by emvaized** [comment]
Sorry, then I could not help with your issue. When I set "pl" as my user language in the extension settings, live translation works just fine — so my suggestion would be, that the extension could not access Google Translate service from your browser, maybe due to some network restrictions which other extension may have set.

**Comment by p1otr** [comment]
How can I debug it? Can I replace "No translation found" tooltip with an actual error message?

**Comment by emvaized** [comment]
You can inspect the relevant code [here](https://github.com/emvaized/selecton-extension/blob/efa7c90d8977abb8de7cb37a7863d0f93dabf451/src/ui/buttons/hover-buttons/translate-button.js#L105), if you'd like

**Comment by p1otr** [comment]
You're right - it was blocked by Privacy Badger extension.

I'm changing bug title to "Please show more meaningful error message when translation service cannot be reached"

**Comment by emvaized** [comment]
I doubt there's any way to make it much more meaningful that this. The request for translation either succeeds or fails – and there may be any reason why it fails, including the basic absence of internet connection. There might be some clues in the message, which gets printed in the developer console when "debug mode" is enabled in settings, but it's unlikely to be useful for a regular user. 

Usually it's just other extensions blocking all requests to Google servers.
