### ISSUE TITLE
It's not working in Google Search (google.com)

### ISSUE THREAD

**Issue by cris2d2** [emvaized/selecton-extension#49]
I really want to ditch Opera's own "Search pop-up" feature in favor of Selecton but your extensions doesn't seem to work on some websites, Google Search (google.com) being one of them. There's no pop up if I select the text. 

Is this a feature or a bug?

**Comment by emvaized** [comment]
Probably a bug, as I don't have any issues with extension on google.com

**Comment by emvaized** [comment]
New version 3.7.0 is released now with better compatibility on some websites. If it still won't work for you, then it might be some conflicts with other extensions you are using. 

Closing this now, feel free to reopen if you still experience problems on google.com
