### ISSUE TITLE
Custom search engines can't get it to work and don't know how

### ISSUE THREAD

**Issue by katastrophe92** [emvaized/selecton-extension#51]
First of all, I LOVE this adon and in my opinion it is the most rich-full of options and customization. Because I'm a noob I do not know what to put after ".com" for search engines. Please tell/explain me how that works. I noticed that the other ones have something at the end. 
Thank you and have a nice day!!!

![16 01 2023  20-38-08](https://user-images.githubusercontent.com/103950507/212756654-9f1b66ed-ddad-42eb-9c78-a601ac173553.png)

**Comment by emvaized** [comment]
Thanks!
Let me quote the corresponding [FAQ](https://github.com/emvaized/selecton-extension#faq) section here:

> Let's use [YouTube](https://youtube.com/) as an example. Go to a website and search for something, like "gold" – your URL will look something like this: `https://www.youtube.com/results?search_query=gold`. You have to grab this url, replace gold with `%s` (placeholder for the searched text), and use it as url for the new search option (Extension options > Custom search options > Add new search option)

**Comment by katastrophe92** [comment]
@emvaized It worked 👍. Using the Settings URL (the one URL if you do not want to save your settings as a Bookmark or Cookie) worket for MetaGer, SearX, DuckDuckGo. But for StartPage it doesn't work. Do you know why? And i just found a Bug: € currency it doesnt save. Rates update interval is 18

**Comment by katastrophe92** [comment]
@emvaized Hi again. After I was done setting up the custom search buttons and tested everything, it was all working great besides StartPage. Now I started my PC and it did not saved the new settings. Does it have a Search buttons limit or how big the .json file can be?

**Comment by emvaized** [comment]
> Does it have a Search buttons

It kinda does — the whole size of storage dedicated to extension's data is limited to 5 Mb. But I don't think you've reached this limit, you have to have **really** many search engines added to exceed it. Most likely settings weren't saved due to the data corruption in some of the search engines, in such cases I recommend to simply delete them and create again.
