### ISSUE TITLE
Support to Microsoft Edge

### ISSUE THREAD

**Issue by simonbcn** [emvaized/selecton-extension#53]
Considering that Microsoft Edge is another Chromium derivative, couldn't it be added in the [Edge extension store](https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home)?

**Comment by emvaized** [comment]
Hi Simon, 
I don't see a lot of sense in this, as Edge supports installing extensions directly from Chrome Web Store

**Comment by simonbcn** [comment]
Ok, I didn't know it.
