### ISSUE TITLE
Unable to Sort Search Buttons, They Revert to Random

### ISSUE THREAD

**Issue by 2Data6** [emvaized/selecton-extension#55]
Hello;

So far, really digging the add-on.  I just have one issue.  I have tried to manually change the order of the Search Buttons after entering those I typically like to have handy.  I have exactly 20 search buttons.  

I manually reordered them by subject and then alphabetically, e.g., search engines first, then online shopping sites, then various sites of different uses.

When I tested the add-on using the “Test the Settings” button at the bottom of the preferences page, I saw that the search buttons were still in the original random order when the drop-down menu appeared and hadn't changed at all.  I tried this on different websites as well, with the same result.

I then reloaded the Preferences page for Selection, and all the changes I had made to re-order the Selection Buttons vanished and were replaced with the random original order.  It was a rather tedious process to use the little arrows up and down to get the Selection Buttons in the order I wanted.  

If this can be figured out, or if there is needed information that might help, please let me know.  Also, not being technically oriented, I may need a little instruction on how to access whatever information you need. 

One other thing occurred to me as I was re-ordering the Selection Buttons.  Would it be possible to incorporate a numbering system as well along with the arrows so that instead of the arrows, we could just renumber their order by simply typing the order they should be in.   For example, (1) Amazon, (2) Bing, (3) Google, etc. 

Thanks so much.

2Data6

<b>System Information</b>

Firefox 111.0 (64 – Bit)
Mac (21.5-inch, Late 2012)
Processor 2.7 GHz Quad-core Intel Core i5
Memory 8 GB 1600 MHz DDR3
Startup Disk – External Samsung SSD
Graphics NVIDIA GeForce GT 640M to 512 MB

**Comment by emvaized** [comment]
Hi! Sorry for long response. 
I think most likely it was the problem with one of your search options being wrongly formatted, or using non-standard characters — because as far as I could tell, you're the first to report such problem. It's really hard to debug problems like this unless we figured out what exact entry causes the problem of saving the search options list.
