### ISSUE TITLE
'&' character in search terms breaks search results

### ISSUE THREAD

**Issue by Wodnic** [emvaized/selecton-extension#7]
Performing a search on a text containing '&' character shows the results only for the part before the &. For example if you try searching for "Asterix & Obelix" it shows only the results for "Asterix". The character should be probably replaced with %26.

**Comment by emvaized** [comment]
Thanks for submitting! 
I can confirm this issue, will fix it in next update today or tomorrow

**Comment by emvaized** [comment]
Should be fixed in 3.0.7
