### ISSUE TITLE
A new tab does not open after the last update.

### ISSUE THREAD

**Issue by gityhubi** [emvaized/selecton-extension#71]
A new tab does not open after the last update. The search is performed in the current tab

**Comment by emvaized** [comment]
Did you mean the regular search button, or custom search buttons in the hover popup?

**Comment by emvaized** [comment]
Thanks for report! I will fix that in the next update. 
Until then, as a workaround please use scroll wheel click on these buttons to open them in a new tab.

**Comment by emvaized** [comment]
Fixed in version 3.7.9
