### ISSUE TITLE
Not show full icon when tick Custom search icon > Show in main panel

### ISSUE THREAD

**Issue by dzungitx** [emvaized/selecton-extension#73]
Now it show like this.
![1](https://github.com/user-attachments/assets/a05cf819-1ddc-4afc-b64c-9fc161a52c91)

When I tick Show in main panel for Custom search
![2](https://github.com/user-attachments/assets/1b70f7b9-e5dc-4e87-8300-9403edc0fdb6)

then it show..
![4](https://github.com/user-attachments/assets/ca7e8b62-f9bd-478f-9918-7cea49152133)

Translate icon has disappeared.

**Comment by emvaized** [comment]
This problem will be fixed in the new update 3.9.0
