### ISSUE TITLE
Add option to show the menu whre the mouse pointer is

### ISSUE THREAD

**Issue by sbstn87** [emvaized/selecton-extension#9]
Hi, can you add an option that causes the menu to open in the place of mouse pointer?

**Comment by emvaized** [comment]
Thanks for suggestion!

I think such a behavior may result sometimes in text selection being covered by tooltip. 
Maybe it should be better aligned to the selection's start/end? E.g. over drag handle closest to cursor

**Comment by sbstn87** [comment]
It won't cover the selected text, if the menu is shown just below the cursor, so yeah - basically over drag handle closest to the cursor.

**Comment by emvaized** [comment]
I was referring to situation like this, for example:
![image](https://user-images.githubusercontent.com/37851576/119084575-b429a700-ba0a-11eb-8fe4-9b0749dae267.png)

Tooltip completely hid the upper drag handle, and also huge part of the selected text. I'm not sure how to resolve this kind of situations

**Comment by sbstn87** [comment]
Maybe make the tooltip to show up "upside-down" - below the selected text?

**Comment by emvaized** [comment]
That's a great idea! 
It will still mess up with with drag handles in some situations, but much less often.

However, there's no such code to display tooltip at bottom and reposition the arrow so it will be on top of tooltip - so it will take some time for me to write it and test how it looks

**Comment by sbstn87** [comment]
Great, I'll be waiting for this one.

**Comment by emvaized** [comment]
I think that's the best it could get:
![Screenshot_20210521_203637](https://user-images.githubusercontent.com/37851576/119176848-3f8b5280-ba74-11eb-9a12-680e537a3e09.png)

**Comment by sbstn87** [comment]
Great! That's exactly what I had in my mind :)

**Comment by emvaized** [comment]
During testings I found out that 'show on bottom' approach doesn't work well in some cases, so I decided to choose compromise solution - when new option is enabled in settings, tooltip will be horizontally aligned to cursor position instead of center of selection. 

So it goes for only dx alignment instead of dx/dy

**Comment by sbstn87** [comment]
I have tried the new option and it is certainly a nice improvement. Thank you!
